apiVersion: v1
data:
  name: {{ print "p2p-devops-test-gitflow" | b64enc }}
  project: {{ print "default" | b64enc }}
  type: {{ print "git" | b64enc }}
  url: {{ print "https://github.com/frannovo/p2p-devops-test-gitflow" | b64enc }}
kind: Secret
metadata:
  name: p2p-devops-test-gitflow-repo
  namespace: argocd
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    argocd.argoproj.io/secret-type: repository
