{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "goapp.fullname" . }}
  labels:
    {{- include "goapp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "goapp.labels" . | nindent 4 }}
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
{{- end -}}