# Dev values for goapp.
replicaCount: 1

image:
  repository: ghcr.io/frannovo/p2p-devops-test-gitflow
  # This sets the pull policy for images.
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 09336623fdf99de044590394e4e116ef93da6d24


autoscaling:
  enabled: false
